### ISSUE TITLE
deleteObject 403 Error

### ISSUE THREAD

**Issue by emericspiroux** [aws/aws-sdk-php-symfony#20]
Hi,

I've got a problem, i trying to delete an image uploaded on my bucket with this code :
```
if (($oldImageName = $user->getUserInfo()->getImageName()) != "" && $this->s3->doesObjectExist('myBucket', $oldImageName)) {
            $this->s3->deleteObject([
                'Bucket' => 'myBucket',
                'Key' => $oldImageName
            ]);
}
```
But i receive a 403 Forbidden error. I succeed to upload images, fetch them but i can't delete them.
Do you know what's the problem ?

Thanks to the team !

**Comment by cjyclaire** [comment]
@emericspiroux Could you double check your permission with the object? Also, may I ask how do you set up the credentials in performing those API calls??

**Comment by emericspiroux** [comment]
I've try to use two methods : 

1- .aws/credentials file : 
```
[default] 
aws_access_key_id = XXXXXXXXXXXXXXXXXX...
aws_secret_access_key = XXXXXXXXXXXXXXXX...
```

2- In my parameter.yml config : 
```
    amazon_s3.key: XXXXXXXXXXXXXXXX...
    amazon_s3.secret: XXXXXXXXXXXXXXXX...
    amazon_s3.region: eu-west-1
```

I use this documentation : http://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingOneObjectUsingPHPSDK.html

But why i can post an object but not delete him with the same method ? it's seems to aws php sdk have all that he need to do the first step but not the second ? It's inside the same method.

**Comment by cjyclaire** [comment]
@emericspiroux The policy is different in performing PUT or DELETE when you assume a role in making API calls, it looks like that is not the problem since you are using profile credentials directly. 

Since Your code looks good to me, and I couldn't reproduce the issue locally with the `deleteObject` API call, could you double check your permission for the object first?

For more API docs for [AWS SDK for PHP V3](http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)

**Comment by emericspiroux** [comment]
Thanks for your testing ! I'll check my permission twice !
